"""
Chat phrases for casino bot to simulate realistic player behavior.
Used by test-bot to add personality and variety to gameplay.
"""

BET_PHRASES = [
    "Let it ride!",
    "Feeling lucky today!",
    "Red is my color!",
    "This is the one!",
    "All in on black!",
    "Time to make some money!",
    "My lucky number!",
    "Got a good feeling about this",
    "Fortune favors the bold!",
    "Let's see what happens",
    "Going with my gut",
    "Third time's the charm",
    "Betting big on this one",
    "Can't lose forever",
    "The streak ends now",
    "I've studied the patterns",
    "Trust the system",
    "This is my moment",
    "Doubling down!",
    "Playing it safe this round",
    "Maximum bet, maximum reward",
    "Following my instincts",
    "The wheel owes me one",
    "Statistical probability says yes",
    "Going all out!",
    "Playing the odds",
    "Red's been hot lately",
    "Black is due",
    "Evens never fail me",
    "Corners are calling my name",
    "Split bet for the win",
    "Straight up or nothing",
    "Covering my bases",
    "Hedging my bets",
    "Risk it for the biscuit!",
    "No guts, no glory",
    "Calculated risk time",
    "Lady Luck, don't fail me now",
    "Here goes nothing!",
    "This feels right",
    "Betting with confidence",
    "Time to turn it around",
    "Starting strong",
    "Keeping the momentum",
    "Changing up my strategy",
    "Back to basics",
    "Going with the classic",
    "High risk, high reward",
    "Conservative play this time",
    "Mixing it up",
    "Same bet, same luck",
    "New round, new chances",
    "The math checks out",
    "Pure intuition",
    "Saw this in a dream",
    "Birthday numbers for luck",
    "Anniversary number!",
    "My favorite combo",
    "Can't argue with success",
    "Time to be bold",
    "Playing it smart",
    "All about timing",
    "Patience pays off",
    "Now's my chance",
    "Seizing the moment",
    "Going for broke!",
    "Testing my theory",
    "The pattern is clear",
    "Random is random, right?",
    "Superstition says go",
    "Logic says bet",
    "Heart over head",
    "Brain says yes",
    "Destiny awaits",
    "Manifesting a win",
    "Positive vibes only",
    "The universe wants me to win",
    "Karma's on my side",
    "Energy feels right",
    "Stars are aligned",
    "Moon phase is perfect",
    "Lucky socks working",
    "Four leaf clover energy",
    "Horseshoe power!",
    "Rabbit's foot charm activated",
    "Fingers crossed!",
    "Knock on wood",
    "Breaking my losing streak",
    "Extending my winning streak",
    "Back in the game",
    "Ready to win big",
    "This table is hot",
    "Dealer looks nervous",
    "I've got this",
    "Confidence is key",
    "Betting smart, betting strong",
    "Here we go again!",
    "One more time!",
    "Last bet paid off",
]

WIN_PHRASES = [
    "Called it!",
    "That's what I'm talking about!",
    "Easy money!",
    "Knew it!",
    "Yes! Yes! Yes!",
    "I'm on fire!",
    "Can't stop won't stop!",
    "The streak continues!",
    "Told you so!",
    "That's how it's done!",
    "Pure skill right there",
    "Lucky charm working!",
    "Boom! Another one!",
    "This is my game!",
    "Crushing it today!",
    "The system works!",
    "Mathematics never lies",
    "Calculated perfectly",
    "Strategy paying off!",
    "Reading the wheel like a book",
    "No surprise there",
    "As expected!",
    "Right on target",
    "Nailed it!",
    "Sweet victory!",
    "Cha-ching!",
    "Money in the bank!",
    "Let's goooo!",
    "Unstoppable!",
    "This is too easy",
    "Making it look simple",
    "Natural talent",
    "Got the magic touch",
    "Winner winner!",
    "Jackpot vibes!",
    "Can't lose today!",
    "Everything's coming up roses",
    "On a roll!",
    "Hot streak activated",
    "This is my table now",
    "Dominating!",
    "They don't call me lucky for nothing",
    "Skill beats luck every time",
    "That's why I bet big",
    "Confidence rewarded!",
    "Trust the process",
    "Patience paid off",
    "Worth the wait!",
    "Doubled my money!",
    "Big win baby!",
]

LOSE_PHRASES = [
    "So close!",
    "Next time for sure",
    "That's rough",
    "Can't win them all",
    "Almost had it",
    "One number off!",
    "The wheel is cruel today",
    "Not my round",
    "Shake it off",
    "Staying positive",
    "Learning experience",
    "That's the game",
    "Variance happens",
    "Unlucky bounce",
    "Tough break",
    "Sometimes it be like that",
    "Back to the drawing board",
    "Need to recalculate",
    "Strategy adjustment needed",
    "Just warming up",
    "Getting the bad luck out early",
    "Setting up for the comeback",
    "This is fine",
    "Not worried yet",
    "Plenty of rounds left",
    "Long game mindset",
    "Still ahead overall",
    "Minor setback",
    "Could've been worse",
    "At least I tried",
    "Gave it a shot",
    "Risk didn't pay off this time",
    "That's gambling",
    "House edge showing",
    "Statistics catching up",
    "Regression to the mean",
    "Expected some losses",
    "Part of the plan",
    "Staying disciplined",
    "Not chasing losses",
    "Sticking to my limits",
    "Responsible gambling",
    "Tomorrow's another day",
    "Fresh start next round",
    "Resetting strategy",
    "Taking a breath",
    "Analyzing what went wrong",
    "Won't make that mistake again",
    "Lesson learned",
    "Character building moment",
]
